# Generated by Django 5.2.9 on 2025-12-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
